#!/bin/sh

# Get script path (only used if environment is relocatable).
if [ -n "${BASH_VERSION:+x}" ] ; then
    SCRIPT_PATH="${BASH_SOURCE[0]}"
    if [ "$SCRIPT_PATH" = "$0" ]; then
        # Only bash has a reasonably robust check for source'dness.
        echo "You must source this script: \$ source $0" >&2
        exit 33
    fi
elif [ -n "${ZSH_VERSION:+x}" ] ; then
    SCRIPT_PATH="${(%):-%x}"
elif [ -n "${KSH_VERSION:+x}" ] ; then
    SCRIPT_PATH="${.sh.file}"
fi

SCRIPT_ROOT=$(realpath $(dirname "${SCRIPT_PATH}"))

# Isaac Sim Setup
export ISAACSIM_PATH="${SCRIPT_ROOT}/third_party/IsaacSim/_build/linux-$(uname -m)/release"
export ISAACSIM_PYTHON_EXE="${ISAACSIM_PATH}/python.sh"
if [[ ":$LD_PRELOAD:" != *":libgomp.so.1:"* ]]; then
    export LD_PRELOAD="$LD_PRELOAD:/lib/$(uname -m)-linux-gnu/libgomp.so.1"
fi

# Isaac Lab Setup
alias isaaclab="${SCRIPT_ROOT}/third_party/IsaacLab/isaaclab.sh"
alias python="${SCRIPT_ROOT}/third_party/IsaacLab/isaaclab.sh -p"
alias pip="${SCRIPT_ROOT}/third_party/IsaacLab/isaaclab.sh -p -m pip"
